export type Formula = {
  id: string;
  name: string;
  formula: string;
  explanation: string[];
  example: string;
  /** Secções da página completa (opcionais — há valores por omissão) */
  intro?: string;
  concept?: string;
  whenToUse?: string;
  exercise?: string;
  answer?: string;
  tips?: string[];
  summary?: string;
};

export type FormulaCategory = {
  id: string;
  name: string;
  emoji: string;
  formulas: Formula[];
};


export const FORMULA_CATEGORIES: FormulaCategory[] = [
  {
    id: "geometria",
    name: "Geometria",
    emoji: "📐",
    formulas: [
      {
        id: "area-triangulo",
        name: "Área do Triângulo",
        formula: "A = (b × h) ÷ 2",
        explanation: [
          "b representa a base do triângulo.",
          "h representa a altura.",
          "Multiplica-se a base pela altura e divide-se por dois.",
        ],
        example: "Se a base é 10 e a altura é 6:\nA = (10 × 6) ÷ 2 = 30",
      },
      {
        id: "area-trapezio",
        name: "Área do Trapézio",
        formula: "A = [(B + b) × h] ÷ 2",
        explanation: ["B é a base maior.", "b é a base menor.", "h é a altura."],
        example: "B = 12, b = 8, h = 5\nA = [(12 + 8) × 5] ÷ 2 = 50",
      },
      {
        id: "area-paralelogramo",
        name: "Área do Paralelogramo",
        formula: "A = b × h",
        explanation: ["b é a base.", "h é a altura."],
        example: "Base = 9 e altura = 4\nA = 9 × 4 = 36",
      },
      {
        id: "area-circulo",
        name: "Área do Círculo",
        formula: "A = π × r²",
        explanation: ["r é o raio do círculo.", "π (pi) vale aproximadamente 3,1416."],
        example: "Raio = 7\nA = π × 7² = π × 49 ≈ 153,94",
      },
      {
        id: "perimetro-circulo",
        name: "Perímetro do Círculo",
        formula: "P = 2 × π × r",
        explanation: ["r é o raio do círculo."],
        example: "Raio = 5\nP = 2 × π × 5 ≈ 31,42",
      },
      {
        id: "volume-cilindro",
        name: "Volume do Cilindro",
        formula: "V = π × r² × h",
        explanation: ["r é o raio da base.", "h é a altura do cilindro."],
        example: "r = 3 e h = 10\nV = π × 9 × 10 ≈ 282,74",
      },
    ],
  },
  {
    id: "algebra",
    name: "Álgebra",
    emoji: "➗",
    formulas: [
      {
        id: "bhaskara",
        name: "Equação do 2.º Grau (Bhaskara)",
        formula: "x = (−b ± √Δ) ÷ (2a), com Δ = b² − 4ac",
        explanation: [
          "a, b e c são os coeficientes de ax² + bx + c = 0.",
          "Δ (delta) indica quantas soluções existem: Δ > 0 duas, Δ = 0 uma, Δ < 0 nenhuma real.",
        ],
        example: "x² − 5x + 6 = 0\nΔ = 25 − 24 = 1 → x = (5 ± 1) ÷ 2 → x = 3 ou x = 2",
      },
      {
        id: "produtos-notaveis",
        name: "Produtos Notáveis",
        formula: "(a + b)² = a² + 2ab + b²",
        explanation: ["Quadrado do primeiro, mais o dobro do produto, mais o quadrado do segundo."],
        example: "(x + 3)² = x² + 6x + 9",
      },
      {
        id: "regra-tres",
        name: "Regra de Três Simples",
        formula: "a ÷ b = c ÷ x  →  x = (b × c) ÷ a",
        explanation: ["Usada quando duas grandezas são diretamente proporcionais."],
        example: "Se 4 cadernos custam 200 MT, 7 cadernos custam:\nx = (200 × 7) ÷ 4 = 350 MT",
      },
    ],
  },
  {
    id: "estatistica",
    name: "Estatística",
    emoji: "📊",
    formulas: [
      {
        id: "media",
        name: "Média Aritmética",
        formula: "x̄ = (soma dos valores) ÷ (número de valores)",
        explanation: ["Somam-se todos os valores e divide-se pela quantidade deles."],
        example: "Notas 12, 14, 16, 18\nx̄ = 60 ÷ 4 = 15",
      },
      {
        id: "variancia",
        name: "Variância",
        formula: "σ² = Σ(xᵢ − x̄)² ÷ n",
        explanation: ["Mede o quanto os valores se afastam da média."],
        example: "Valores 2, 4, 6 (x̄ = 4)\nσ² = (4 + 0 + 4) ÷ 3 ≈ 2,67",
      },
      {
        id: "desvio",
        name: "Desvio Padrão",
        formula: "σ = √(variância)",
        explanation: ["É a raiz quadrada da variância, na mesma unidade dos dados."],
        example: "Se σ² = 2,67 então σ ≈ 1,63",
      },
    ],
  },
  {
    id: "contabilidade",
    name: "Contabilidade",
    emoji: "🧾",
    formulas: [
      {
        id: "equacao-patrimonial",
        name: "Equação Patrimonial",
        formula: "Activo = Passivo + Capital Próprio",
        explanation: ["Tudo o que a empresa possui é financiado por dívidas ou por capital próprio."],
        example: "Activo 500.000 MT e Passivo 200.000 MT\nCapital Próprio = 300.000 MT",
      },
      {
        id: "resultado-liquido",
        name: "Resultado Líquido",
        formula: "Resultado = Proveitos − Custos",
        explanation: ["Se o resultado for positivo há lucro; se for negativo há prejuízo."],
        example: "Proveitos 80.000 MT e Custos 55.000 MT\nResultado = 25.000 MT de lucro",
      },
    ],
  },
  {
    id: "gestao",
    name: "Gestão",
    emoji: "💼",
    formulas: [
      {
        id: "ponto-critico",
        name: "Ponto Crítico de Vendas",
        formula: "PC = Custos Fixos ÷ (Preço − Custo Variável)",
        explanation: ["Indica quantas unidades é preciso vender para não ter prejuízo."],
        example: "Custos fixos 30.000 MT, preço 100 MT, custo variável 40 MT\nPC = 30.000 ÷ 60 = 500 unidades",
      },
      {
        id: "margem",
        name: "Margem de Lucro",
        formula: "Margem (%) = (Lucro ÷ Vendas) × 100",
        explanation: ["Mostra quanto de cada 100 MT vendidos fica como lucro."],
        example: "Lucro 15.000 MT e vendas 60.000 MT\nMargem = 25%",
      },
    ],
  },
  {
    id: "economia",
    name: "Economia",
    emoji: "📈",
    formulas: [
      {
        id: "pib",
        name: "PIB pela Despesa",
        formula: "PIB = C + I + G + (X − M)",
        explanation: [
          "C é o consumo das famílias, I o investimento, G os gastos do Estado.",
          "X são as exportações e M as importações.",
        ],
        example: "C=500, I=200, G=150, X=100, M=80\nPIB = 870",
      },
      {
        id: "inflacao",
        name: "Taxa de Inflação",
        formula: "π = [(IPC₁ − IPC₀) ÷ IPC₀] × 100",
        explanation: ["Compara o índice de preços de dois períodos."],
        example: "IPC₀ = 120 e IPC₁ = 132\nπ = (12 ÷ 120) × 100 = 10%",
      },
    ],
  },
  {
    id: "programacao",
    name: "Programação",
    emoji: "💻",
    formulas: [
      {
        id: "complexidade",
        name: "Complexidade de Algoritmos",
        formula: "O(n), O(log n), O(n²)",
        explanation: [
          "O(n) cresce em proporção ao número de dados.",
          "O(log n) cresce muito devagar (pesquisa binária).",
          "O(n²) cresce rapidamente (ciclos encaixados).",
        ],
        example: "Percorrer uma lista de 1000 elementos com dois ciclos encaixados → 1.000.000 operações.",
      },
      {
        id: "conversao-binaria",
        name: "Conversão Decimal → Binário",
        formula: "Divisões sucessivas por 2, lendo os restos de baixo para cima",
        explanation: ["Divide-se o número por 2 até chegar a zero e junta-se os restos ao contrário."],
        example: "13 → 1101",
      },
    ],
  },
  {
    id: "essenciais",
    name: "20 Fórmulas Essenciais",
    emoji: "⭐",
    formulas: [
      {
        id: "pitagoras",
        name: "Teorema de Pitágoras",
        formula: "a² + b² = c²",
        intro: "É a fórmula mais usada na geometria e serve para relacionar os três lados de um triângulo rectângulo.",
        concept: "Num triângulo rectângulo, o quadrado da hipotenusa é igual à soma dos quadrados dos catetos.",
        whenToUse: "Sempre que existir um ângulo de 90° e for preciso descobrir um lado do triângulo, distâncias ou diagonais.",
        explanation: ["a e b são os catetos (lados que formam o ângulo recto).", "c é a hipotenusa (o lado maior, oposto ao ângulo recto)."],
        example: "Catetos 3 e 4:\n3² + 4² = 9 + 16 = 25\nc = √25 = 5",
        exercise: "Um triângulo rectângulo tem catetos de 6 cm e 8 cm. Qual é a hipotenusa?",
        answer: "6² + 8² = 36 + 64 = 100 → c = √100 = 10 cm",
        tips: ["Confirme sempre qual é a hipotenusa antes de substituir.", "A hipotenusa é sempre o maior lado."],
        summary: "a² + b² = c² relaciona os catetos com a hipotenusa num triângulo rectângulo.",
      },
      {
        id: "bhaskara-essencial",
        name: "Fórmula de Bhaskara",
        formula: "x = (−b ± √Δ) / 2a,  com Δ = b² − 4ac",
        intro: "Resolve qualquer equação do 2.º grau do tipo ax² + bx + c = 0.",
        concept: "Primeiro calcula-se o discriminante Δ e depois aplicam-se as duas soluções possíveis.",
        whenToUse: "Sempre que a equação tiver um termo com x².",
        explanation: ["a, b e c são os coeficientes da equação.", "Δ > 0 dá duas soluções, Δ = 0 dá uma, Δ < 0 não tem solução real."],
        example: "x² − 6x + 9 = 0\nΔ = (−6)² − 4 × 1 × 9 = 36 − 36 = 0\nx = 6 / 2 = 3",
        exercise: "Resolva x² − 5x + 6 = 0.",
        answer: "Δ = 25 − 24 = 1 → x = (5 ± 1) / 2 → x = 3 ou x = 2",
        tips: ["Escreva sempre a, b e c antes de calcular.", "Não esqueça o sinal negativo de b."],
        summary: "Calcule Δ, depois x = (−b ± √Δ) / 2a.",
      },
      {
        id: "area-retangulo",
        name: "Área do Rectângulo",
        formula: "A = b × h",
        intro: "Mede a superfície de um rectângulo.",
        concept: "Multiplica-se a base pela altura.",
        whenToUse: "Terrenos, salas, paredes e qualquer superfície rectangular.",
        explanation: ["b é a base.", "h é a altura."],
        example: "b = 8 m e h = 5 m → A = 40 m²",
        exercise: "Uma sala tem 7 m por 4 m. Qual é a área?",
        answer: "A = 7 × 4 = 28 m²",
        tips: ["As unidades têm de ser iguais antes de multiplicar."],
        summary: "Área do rectângulo = base × altura.",
      },
      {
        id: "area-triangulo-essencial",
        name: "Área do Triângulo",
        formula: "A = (b × h) / 2",
        intro: "Calcula a superfície de qualquer triângulo.",
        concept: "É metade da área do rectângulo com a mesma base e altura.",
        whenToUse: "Terrenos triangulares, telhados e figuras compostas.",
        explanation: ["b é a base.", "h é a altura relativa a essa base."],
        example: "b = 10 e h = 6 → A = 60 / 2 = 30",
        exercise: "Base 12 cm e altura 5 cm. Qual é a área?",
        answer: "A = (12 × 5) / 2 = 30 cm²",
        tips: ["A altura é perpendicular à base, não é o lado inclinado."],
        summary: "Área do triângulo = base × altura, a dividir por 2.",
      },
      {
        id: "area-circulo-essencial",
        name: "Área do Círculo",
        formula: "A = π × r²",
        intro: "Mede a superfície de um círculo.",
        concept: "Depende apenas do raio.",
        whenToUse: "Rodas, tampas, depósitos e figuras circulares.",
        explanation: ["r é o raio.", "π ≈ 3,1416."],
        example: "r = 7 → A = π × 49 ≈ 153,94",
        exercise: "Um círculo tem raio 3 cm. Qual é a área?",
        answer: "A = π × 9 ≈ 28,27 cm²",
        tips: ["Se lhe derem o diâmetro, divida por 2 para obter o raio."],
        summary: "Área do círculo = π × raio ao quadrado.",
      },
      {
        id: "perimetro-circulo-essencial",
        name: "Perímetro do Círculo",
        formula: "P = 2 × π × r",
        intro: "Mede o contorno de um círculo.",
        concept: "É o comprimento da circunferência.",
        whenToUse: "Voltas de roda, cercas circulares e comprimentos de arco.",
        explanation: ["r é o raio."],
        example: "r = 5 → P = 2 × π × 5 ≈ 31,42",
        exercise: "Raio 10 cm. Qual é o perímetro?",
        answer: "P = 2 × π × 10 ≈ 62,83 cm",
        tips: ["P também se escreve π × diâmetro."],
        summary: "Perímetro do círculo = 2 × π × raio.",
      },
      {
        id: "volume-cubo",
        name: "Volume do Cubo",
        formula: "V = a³",
        intro: "Calcula o espaço ocupado por um cubo.",
        concept: "Todas as arestas têm o mesmo comprimento.",
        whenToUse: "Caixas cúbicas, blocos e depósitos.",
        explanation: ["a é a medida da aresta."],
        example: "a = 4 → V = 4³ = 64",
        exercise: "Aresta 3 m. Qual é o volume?",
        answer: "V = 27 m³",
        tips: ["O resultado vem sempre em unidades cúbicas."],
        summary: "Volume do cubo = aresta × aresta × aresta.",
      },
      {
        id: "volume-cilindro-essencial",
        name: "Volume do Cilindro",
        formula: "V = π × r² × h",
        intro: "Calcula a capacidade de um cilindro.",
        concept: "É a área da base circular multiplicada pela altura.",
        whenToUse: "Depósitos, latas, tubos e reservatórios.",
        explanation: ["r é o raio da base.", "h é a altura."],
        example: "r = 3 e h = 10 → V = π × 9 × 10 ≈ 282,74",
        exercise: "r = 2 m e h = 5 m. Qual é o volume?",
        answer: "V = π × 4 × 5 ≈ 62,83 m³",
        tips: ["1 m³ corresponde a 1000 litros."],
        summary: "Volume do cilindro = π × r² × altura.",
      },
      {
        id: "media-essencial",
        name: "Média Aritmética",
        formula: "x̄ = soma dos valores / número de valores",
        intro: "Resume um conjunto de dados num único valor.",
        concept: "Distribui igualmente o total pelos elementos.",
        whenToUse: "Notas, salários, temperaturas e qualquer conjunto de dados.",
        explanation: ["Some todos os valores.", "Divida pela quantidade de valores."],
        example: "12, 14, 16, 18 → 60 / 4 = 15",
        exercise: "Notas 10, 15 e 20. Qual é a média?",
        answer: "(10 + 15 + 20) / 3 = 15",
        tips: ["Valores muito altos ou muito baixos alteram bastante a média."],
        summary: "Média = total dos valores dividido pela quantidade.",
      },
      {
        id: "percentagem",
        name: "Percentagem",
        formula: "P = (parte / total) × 100",
        intro: "Indica quanto uma parte representa em cada 100.",
        concept: "Compara a parte com o total.",
        whenToUse: "Descontos, notas, juros e estatísticas.",
        explanation: ["parte é o valor considerado.", "total é o valor de referência."],
        example: "15 de 60 → (15 / 60) × 100 = 25%",
        exercise: "Numa turma de 40 alunos, 30 passaram. Qual é a percentagem?",
        answer: "(30 / 40) × 100 = 75%",
        tips: ["Para achar a parte: parte = total × percentagem / 100."],
        summary: "Percentagem = parte a dividir pelo total, vezes 100.",
      },
      {
        id: "regra-tres-essencial",
        name: "Regra de Três Simples",
        formula: "a / b = c / x  →  x = (b × c) / a",
        intro: "Resolve problemas de proporcionalidade directa.",
        concept: "Multiplica-se em cruz e isola-se o valor desconhecido.",
        whenToUse: "Preços, receitas, distâncias e conversões.",
        explanation: ["a e b são o primeiro par.", "c e x são o segundo par."],
        example: "4 cadernos custam 200 MT. 7 cadernos: x = (200 × 7) / 4 = 350 MT",
        exercise: "Se 3 kg custam 150 MT, quanto custam 5 kg?",
        answer: "x = (150 × 5) / 3 = 250 MT",
        tips: ["Confirme se as grandezas são directamente proporcionais."],
        summary: "Multiplique em cruz e divida pelo valor conhecido.",
      },
      {
        id: "produtos-notaveis-essencial",
        name: "Produtos Notáveis",
        formula: "(a + b)² = a² + 2ab + b²",
        intro: "Atalho para desenvolver expressões algébricas.",
        concept: "Quadrado do primeiro, mais o dobro do produto, mais o quadrado do segundo.",
        whenToUse: "Simplificar expressões e resolver equações.",
        explanation: ["a e b são os termos do binómio."],
        example: "(x + 3)² = x² + 6x + 9",
        exercise: "Desenvolva (2x + 5)².",
        answer: "4x² + 20x + 25",
        tips: ["(a − b)² = a² − 2ab + b² e (a + b)(a − b) = a² − b²."],
        summary: "O quadrado de uma soma tem sempre três termos.",
      },
      {
        id: "juros-simples",
        name: "Juros Simples",
        formula: "J = C × i × t",
        intro: "Calcula o juro que um capital gera ao longo do tempo.",
        concept: "O juro incide sempre sobre o capital inicial.",
        whenToUse: "Empréstimos curtos e cálculos financeiros básicos.",
        explanation: ["C é o capital inicial.", "i é a taxa por período (em decimal).", "t é o tempo, no mesmo período da taxa."],
        example: "C = 10.000 MT, i = 2% ao mês, t = 6 meses\nJ = 10.000 × 0,02 × 6 = 1.200 MT",
        exercise: "Capital 5.000 MT a 3% ao mês durante 4 meses. Qual é o juro?",
        answer: "J = 5.000 × 0,03 × 4 = 600 MT",
        tips: ["Transforme sempre a percentagem em decimal (2% = 0,02)."],
        summary: "Juro simples = capital × taxa × tempo.",
      },
      {
        id: "juros-compostos",
        name: "Juros Compostos",
        formula: "M = C × (1 + i)^t",
        intro: "Calcula o montante quando o juro rende juro.",
        concept: "Cada período rende sobre o valor acumulado do período anterior.",
        whenToUse: "Poupanças, investimentos e empréstimos longos.",
        explanation: ["M é o montante final.", "C é o capital inicial.", "i é a taxa por período.", "t é o número de períodos."],
        example: "C = 10.000 MT, i = 2% ao mês, t = 3 meses\nM = 10.000 × 1,02³ ≈ 10.612,08 MT",
        exercise: "Capital 2.000 MT a 5% ao ano durante 2 anos. Qual é o montante?",
        answer: "M = 2.000 × 1,05² = 2.205 MT",
        tips: ["O juro é M − C."],
        summary: "Montante composto = capital × (1 + taxa) elevado ao tempo.",
      },
      {
        id: "trigonometria-fundamental",
        name: "Relação Fundamental da Trigonometria",
        formula: "sen²x + cos²x = 1",
        intro: "Liga o seno e o cosseno de um mesmo ângulo.",
        concept: "Para qualquer ângulo, a soma dos quadrados do seno e do cosseno vale 1.",
        whenToUse: "Quando conhece o seno e precisa do cosseno (ou o contrário).",
        explanation: ["sen x é o seno do ângulo.", "cos x é o cosseno do mesmo ângulo."],
        example: "Se sen x = 0,6 então cos²x = 1 − 0,36 = 0,64 → cos x = 0,8",
        exercise: "Se cos x = 0,5, qual é o valor de sen x (ângulo do 1.º quadrante)?",
        answer: "sen²x = 1 − 0,25 = 0,75 → sen x ≈ 0,87",
        tips: ["Atenção ao sinal conforme o quadrante."],
        summary: "sen²x + cos²x é sempre igual a 1.",
      },
      {
        id: "razoes-trigonometricas",
        name: "Razões Trigonométricas",
        formula: "sen = cateto oposto / hipotenusa;  cos = cateto adjacente / hipotenusa;  tg = oposto / adjacente",
        intro: "Relacionam ângulos e lados num triângulo rectângulo.",
        concept: "Cada razão compara dois lados do triângulo.",
        whenToUse: "Alturas, distâncias e rampas com ângulos conhecidos.",
        explanation: ["O cateto oposto está à frente do ângulo.", "O cateto adjacente está encostado ao ângulo."],
        example: "Hipotenusa 10 e cateto oposto 6 → sen = 0,6",
        exercise: "Num triângulo rectângulo, oposto = 4 e adjacente = 3. Qual é a tangente?",
        answer: "tg = 4 / 3 ≈ 1,33",
        tips: ["Memorize: SOH-CAH-TOA."],
        summary: "Seno, cosseno e tangente são razões entre lados.",
      },
      {
        id: "equacao-recta",
        name: "Equação da Recta",
        formula: "y = mx + b",
        intro: "Descreve uma linha recta no plano.",
        concept: "m é o declive e b é a ordenada na origem.",
        whenToUse: "Gráficos, funções afins e problemas de proporcionalidade.",
        explanation: ["m indica a inclinação: m = (y₂ − y₁) / (x₂ − x₁).", "b é o ponto onde a recta corta o eixo y."],
        example: "m = 2 e b = 3 → y = 2x + 3; para x = 4, y = 11",
        exercise: "Escreva a equação da recta que passa por (0, 1) com declive 3.",
        answer: "y = 3x + 1",
        tips: ["Declive positivo sobe, negativo desce."],
        summary: "Recta: y = declive × x + ordenada na origem.",
      },
      {
        id: "distancia-dois-pontos",
        name: "Distância entre Dois Pontos",
        formula: "d = √[(x₂ − x₁)² + (y₂ − y₁)²]",
        intro: "Mede a distância no plano cartesiano.",
        concept: "É uma aplicação directa do teorema de Pitágoras.",
        whenToUse: "Geometria analítica, mapas e coordenadas.",
        explanation: ["(x₁, y₁) e (x₂, y₂) são os pontos."],
        example: "A(1, 2) e B(4, 6):\nd = √(9 + 16) = √25 = 5",
        exercise: "Distância entre (0,0) e (6,8)?",
        answer: "d = √(36 + 64) = 10",
        tips: ["A ordem dos pontos não altera o resultado."],
        summary: "Distância = raiz da soma dos quadrados das diferenças.",
      },
      {
        id: "identidade-euler",
        name: "Identidade de Euler",
        formula: "e^(iπ) + 1 = 0",
        intro: "É considerada a fórmula mais bela da matemática.",
        concept: "Reúne cinco constantes fundamentais: e, i, π, 1 e 0.",
        whenToUse: "Matemática avançada, números complexos e engenharia.",
        explanation: ["e ≈ 2,718 é o número de Euler.", "i é a unidade imaginária (i² = −1).", "π ≈ 3,1416."],
        example: "Da fórmula de Euler e^(ix) = cos x + i·sen x, com x = π:\ne^(iπ) = −1 + 0 → e^(iπ) + 1 = 0",
        exercise: "Qual é o valor de e^(iπ)?",
        answer: "e^(iπ) = −1",
        tips: ["Aparece muito em análise complexa e sinais."],
        summary: "e elevado a iπ mais 1 é igual a zero.",
      },
      {
        id: "euler-poliedros",
        name: "Fórmula de Euler para Poliedros",
        formula: "V + F − A = 2",
        intro: "Relaciona vértices, faces e arestas de um poliedro convexo.",
        concept: "Em qualquer poliedro convexo o resultado é sempre 2.",
        whenToUse: "Geometria espacial e verificação de sólidos.",
        explanation: ["V é o número de vértices.", "F é o número de faces.", "A é o número de arestas."],
        example: "Cubo: V = 8, F = 6, A = 12 → 8 + 6 − 12 = 2",
        exercise: "Um poliedro tem 5 faces e 8 arestas. Quantos vértices tem?",
        answer: "V = 2 + A − F = 2 + 8 − 5 = 5 vértices",
        tips: ["Só é válida para poliedros convexos."],
        summary: "Vértices + Faces − Arestas = 2.",
      },
    ],
  },
];


export function findFormula(id: string) {
  for (const cat of FORMULA_CATEGORIES) {
    const f = cat.formulas.find((x) => x.id === id);
    if (f) return { category: cat, formula: f };
  }
  return null;
}
