/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppTrabalhosRouteImport } from './routes/_app.trabalhos'
import { Route as AppTestesRouteImport } from './routes/_app.testes'
import { Route as AppSuporteRouteImport } from './routes/_app.suporte'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPagamentosRouteImport } from './routes/_app.pagamentos'
import { Route as AppExerciciosRouteImport } from './routes/_app.exercicios'
import { Route as AppExamesRouteImport } from './routes/_app.exames'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAfiliadosRouteImport } from './routes/_app.afiliados'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrabalhosRoute = AppTrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => AppRoute,
} as any)
const AppTestesRoute = AppTestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciciosRoute = AppExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AppRoute,
} as any)
const AppExamesRoute = AppExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAfiliadosRoute = AppAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/afiliados': typeof AppAfiliadosRoute
  '/chat': typeof AppChatRoute
  '/exames': typeof AppExamesRoute
  '/exercicios': typeof AppExerciciosRoute
  '/pagamentos': typeof AppPagamentosRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/suporte': typeof AppSuporteRoute
  '/testes': typeof AppTestesRoute
  '/trabalhos': typeof AppTrabalhosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/afiliados': typeof AppAfiliadosRoute
  '/chat': typeof AppChatRoute
  '/exames': typeof AppExamesRoute
  '/exercicios': typeof AppExerciciosRoute
  '/pagamentos': typeof AppPagamentosRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/suporte': typeof AppSuporteRoute
  '/testes': typeof AppTestesRoute
  '/trabalhos': typeof AppTrabalhosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/afiliados': typeof AppAfiliadosRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/exames': typeof AppExamesRoute
  '/_app/exercicios': typeof AppExerciciosRoute
  '/_app/pagamentos': typeof AppPagamentosRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/suporte': typeof AppSuporteRoute
  '/_app/testes': typeof AppTestesRoute
  '/_app/trabalhos': typeof AppTrabalhosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/afiliados'
    | '/chat'
    | '/exames'
    | '/exercicios'
    | '/pagamentos'
    | '/perfil'
    | '/planos'
    | '/suporte'
    | '/testes'
    | '/trabalhos'
    | '/api/chat'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/afiliados'
    | '/chat'
    | '/exames'
    | '/exercicios'
    | '/pagamentos'
    | '/perfil'
    | '/planos'
    | '/suporte'
    | '/testes'
    | '/trabalhos'
    | '/api/chat'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/afiliados'
    | '/_app/chat'
    | '/_app/exames'
    | '/_app/exercicios'
    | '/_app/pagamentos'
    | '/_app/perfil'
    | '/_app/planos'
    | '/_app/suporte'
    | '/_app/testes'
    | '/_app/trabalhos'
    | '/api/chat'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trabalhos': {
      id: '/_app/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof AppTrabalhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/testes': {
      id: '/_app/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof AppTestesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suporte': {
      id: '/_app/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagamentos': {
      id: '/_app/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercicios': {
      id: '/_app/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof AppExerciciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exames': {
      id: '/_app/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof AppExamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/afiliados': {
      id: '/_app/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AppAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAfiliadosRoute: typeof AppAfiliadosRoute
  AppChatRoute: typeof AppChatRoute
  AppExamesRoute: typeof AppExamesRoute
  AppExerciciosRoute: typeof AppExerciciosRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppTestesRoute: typeof AppTestesRoute
  AppTrabalhosRoute: typeof AppTrabalhosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAfiliadosRoute: AppAfiliadosRoute,
  AppChatRoute: AppChatRoute,
  AppExamesRoute: AppExamesRoute,
  AppExerciciosRoute: AppExerciciosRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppTestesRoute: AppTestesRoute,
  AppTrabalhosRoute: AppTrabalhosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
